apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
 name: mattermost-app
 namespace: mm-app
 labels:
  name: mattermost
  app: mattermost-app
spec:
 componentKinds:
 - group: apps.open-cluster-management.io
   kind: Subscription
 selector:
  matchLabels:
   app: mattermost-app
