apiVersion: app.ibm.com/v1alpha1
kind: PlacementRule
metadata:
  name: mattermostrule
  namespace: mm-app
  labels:
    name: mattermostrule
    app: mattermost-app
spec:
  clusterReplicas: 1
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterSelector:
    matchExpressions:
    - key: environment
      operator: In
      values:
      - dev
